apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: goofy-cdn
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer  # Pour obtenir une IP externe
