services:
  cdn:
    build:
      context: .
      dockerfile: docker/cdn/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./app/CDN:/app
  backend:
    build:
      context: .
      dockerfile: docker/back/Dockerfile.dev
    ports:
      - "8082:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - GIN_MODE=debug
    volumes:
      - ./app/back:/app
    networks:
      - goofy-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - goofy-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - goofy-network
    volumes:
      - redis-data:/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - goofy-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - goofy-network
    depends_on:
      - prometheus

networks:
  goofy-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
  grafana-data:
