apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: goofy-cdn
type: Opaque
stringData:
  mongodb-uri: "mongodb://localhost:27017/goofy"
  jwt-secret: "local-development-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: monitoring
type: Opaque
stringData:
  grafana-admin-password: "admin"
